apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: callme-service
  labels:
    app.openshift.io/runtime: spring-boot
  annotations:
    serving.knative.dev/rollout-duration: "300s"
spec:
  template:
    metadata:
      labels:
        app.openshift.io/runtime: spring-boot
    spec:
      containers:
      - name: callme
        image: piomin/callme-service:1.1
        ports:
          - containerPort: 8080
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace